### ISSUE TITLE
Sorting bugs by a component

### ISSUE THREAD

**Issue by TyDraniu** [MrOtherGuy/fx-nightly-changelog#1]
Hi, 

could you sort bugs by a component? 
Thanks.

**Comment by MrOtherGuy** [comment]
I know I should do something and I've been thinking if it should be sorted by status or component, both or something else. 

But I suppose sorted by component makes the most sense if it's not sortable by user. Anyway, I'll look into this

**Comment by MrOtherGuy** [comment]
Ok. The already generated pages are left as is, but new ones from 2019-11-15 onwards should be alphabetically sorted by product:component
